/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rodolphe_colorizer_OpenCVTasks */

#ifndef _Included_com_rodolphe_colorizer_OpenCVTasks
#define _Included_com_rodolphe_colorizer_OpenCVTasks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rodolphe_colorizer_OpenCVTasks
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rodolphe_colorizer_OpenCVTasks_test
  (JNIEnv *, jclass);

/*
 * Class:     com_rodolphe_colorizer_OpenCVTasks
 * Method:    colorize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/rodolphe/colorizer/JniReturn;
 */
JNIEXPORT jobject JNICALL Java_com_rodolphe_colorizer_OpenCVTasks_colorize
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_rodolphe_colorizer_OpenCVTasks
 * Method:    bwize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/rodolphe/colorizer/JniReturn;
 */
JNIEXPORT jobject JNICALL Java_com_rodolphe_colorizer_OpenCVTasks_bwize
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
